import 'bootstrap/dist/css/bootstrap.css';
import Header from './component/Header/page';

export const metadata = {
  title: 'Home Page Botak',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
