import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import 'bootstrap/dist/css/bootstrap.css';
import Header from './component/Header/page';
config.autoAddCss = false;

export const metadata = {
  title: 'Home Page Botak',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <base href="/"></base>
      </head>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
